name: MLOps Pipeline - Train and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  RESOURCE_GROUP: MLOps_Projects
  APP_SERVICE_NAME: mlops-project-nine-webapp
  ACR_NAME: mlopsprojectnine
  IMAGE_NAME: mlops-project-nine
  DOCKERFILE_PATH: .

jobs:
  train-model:
    name: Train and Save Model
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install -e .
        
    - name: Run Training Pipeline
      env:
        CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
        CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
        BLOB_NAME: ${{ secrets.BLOB_NAME }}
      run: |
        python pipeline/training_pipeline.py
        
    - name: Upload Trained Model
      uses: actions/upload-artifact@v4  # Atualizado para v4
      with:
        name: trained-model
        path: |
          model/model.joblib
          config/paths_config.py
        retention-days: 1

  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: train-model
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download Model Artifact
      uses: actions/download-artifact@v4  # Atualizado para v4
      with:
        name: trained-model
        path: artifact-download

    - name: Move Model to Correct Location
      run: |
        mkdir -p model config
        mv artifact-download/model/model.joblib model/
        mv artifact-download/config/paths_config.py config/
        rm -rf artifact-download

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ env.ACR_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.DOCKERFILE_PATH }}
        push: true
        tags: |
          ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      run: |
        az webapp config container set \
          --name ${{ env.APP_SERVICE_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --docker-custom-image-name ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Update App Settings
      run: |
        az webapp config appsettings set \
          --name ${{ env.APP_SERVICE_NAME }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --settings \
            BLOB_NAME="${{ secrets.BLOB_NAME }}" \
            CONTAINER_NAME="${{ secrets.CONTAINER_NAME }}" \
            CONNECTION_STRING="${{ secrets.CONNECTION_STRING }}"

    - name: Restart App Service
      run: |
        az webapp restart --name ${{ env.APP_SERVICE_NAME }} --resource-group ${{ env.RESOURCE_GROUP }}